# Generated by Django 3.2.11 on 2023-10-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessQuantityAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('norm', models.CharField(max_length=128)),
                ('predict', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AccessQuantityCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('norm', models.CharField(max_length=128)),
                ('predict', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=128)),
                ('p_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('session', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('session', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('session', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AlertMessageAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm_num', models.CharField(max_length=32)),
                ('alert_num', models.CharField(max_length=32)),
                ('exception_num', models.CharField(max_length=32)),
            ],
        ),
    ]
