# Generated by Django 3.2.11 on 2023-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=128)),
                ('p_number', models.CharField(max_length=128)),
            ],
        ),
    ]
